#!/bin/sh

# Backblaze B2 configuration variables
BACKUP_ACCOUNT="AAA"
BACKUP_KEY="BBB"
BACKUP_BUCKET="CCC"
BACKUP_DIR="backups"

BACKUP_URL="b2://${BACKUP_KEY}:${BACKUP_SECRET}@${BACKUP_BUCKET}/${BACKUP_DIR}"

# S3 Configuration variables
export AWS_ACCESS_KEY_ID="AAA"
export AWS_SECRET_ACCESS_KEY="BBB"
BACKUP_BUCKET="CCC"
BACKUP_PROVIDER="DDD"

BACKUP_URL="s3://${BACKUP_PROVIDER}/${BACKUP_BUCKET}/"

# Local directory to backup
LOCAL_DIR="/home/sindre"

# GPG key (last 8 characters)
ENC_KEY="EEEEEEEE"
SGN_KEY="FFFFFFFF"
export PASSPHRASE="GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
export SIGN_PASSPHRASE="HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
